### ISSUE TITLE
about test dataset

### ISSUE THREAD

**Issue by KAIIIS** [YichiCS/Diffusion-Noise-Feature#9] opened 2024-09-12 02:11 UTC
Thank you for your great work. 
I was wondering if you used only fake samples when testing with the CNNSpot dataset. Here are the A.P. results of my tests, and almost all of the real samples were detected as fake.

I used the checkpoint res256np_ddim20_lsun.pth

adm: 1.000
ddpm: 1.000
iddpm: 1.000
ldm: 1.000
pndm: 1.000
sdv1: 1.000
sdv2: 1.000
vqdiffusion: 1.000
mean: 1.000

progan: 0.542
stylegan: 0.533
stylegan2: 0.476
biggan: 0.528
cyclegan: 0.508
stargan: 0.522
gaugan: 0.513
deepfake: 0.500
mean: 0.515

**Comment by YichiCS** [comment] 2024-09-12 02:17
Hello, we simply use the real image in the DF, which may introduce the bias caused by the image format like JPEG or PNG. So we retrain the model under a new setting that all the image are convert in same image format in our new research. The new result and new weight will be released in following days.

**Closed as completed** 2024-10-31 04:22 UTC
